spring:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:/data/employeedb
    driver-class-name: org.h2.Driver
    username: test
    password: testpwd
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  application:
    name: EMPLOYEE-SERVICE
server:
  port: 8081
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
